services:
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mqtt
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - luna_mqtt_data:/mosquitto/data
      - luna_mqtt_log:/mosquitto/log
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/mosquitto.passwd:/mosquitto/config/mosquitto.passwd

  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - 'luna_redis_data:/bitnami/redis/data'

  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=luna
    volumes:
      - luna_pg_data:/bitnami/postgresql

volumes:
  luna_pg_data:
  luna_mqtt_log:
  luna_mqtt_data:
  luna_redis_data:
